version: "3"

services:
  loki:
    image: grafana/loki:2.7.3
    network_mode: "bridge"
    volumes:
      - ./loki/config:/etc/loki
      - ./loki/data:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    user: 0:0

  promtail:
    image: grafana/promtail:2.7.3
    network_mode: "bridge"
    volumes:
      - /var/log:/var/log
      - ./promtail:/etc/promtail
      - ./promtail/tmp:/tmp
    command: -config.file=/etc/promtail/config.yml
    user: 0:0

  grafana:
    image: grafana/grafana:9.1.4
    network_mode: "bridge"
    ports:
      - "4000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=test1234
    user: 0:0