version: '3.3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    secrets:
      - mysql_pw
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_pw
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql/config-file.cnf:/etc/mysql/conf.d/config-file.cnf
    command: 
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_0900_ai_ci"
      - "--default-time_zone=+8:00"

secrets: 
  mysql_pw: 
    file: ./secrets/mysql/pw